CREATE TABLE [Platform].[tblLog]
(
	[LogID] INT NOT NULL IDENTITY(1, 1),
	[ObjectID] UNIQUEIDENTIFIER NOT NULL,
	[Message] NVARCHAR(200) NOT NULL,
	[CreatedTimestamp] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_tblLog_CreatedTimestamp] DEFAULT SYSUTCDATETIME()

	CONSTRAINT [PK_tblLog_LogID] PRIMARY KEY CLUSTERED ([LogID])
);
